[package]
name = "job"
version = "0.1.0"
authors = ["Vlad Nedelcu <nedelcuvd@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies]
num-bigint = "0.4.2"

[dependencies.elrond-wasm]
version = "0.35.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.35.0"
