[package]
name = "job-factory-meta"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2018"
publish = false

[dev-dependencies]
[dependencies.job-factory]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.0"
