[package]
name = "job-abi"
version = "0.0.0"
authors = [ "Claudiu-Marcel Bruda <claudiu.bruda@elrond.com>",]
edition = "2018"
publish = false

[dependencies.job]
path = ".."

[dependencies.elrond-wasm]
version = "0.18.1"

[dependencies.elrond-wasm-debug]
version = "0.18.1"
